version: '3.8'
services:
  davinci:
    environment:
      - TZ=Asia/Shanghai
      - SCREENSHOT_REMOTE_WEBDRIVER_URL=http://chrome:4444/wd/hub
    image: "bi"
    ports:
      - 58080:8080
    restart: always
    volumes:
      - ./config/application.yml:/opt/davinci/config/application.yml:rw
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
    environment:
      - TZ=Asia/Shanghai
